const chart=document.getElementById('chart');let end_sound;const settingEndSound=document.getElementById('setting-end-sound');endSounds.forEach((sound,index)=>{const button=document.createElement('button');button.className='difficulty__button';button.setAttribute('value',sound.url);if(index==0){button.classList.add('current');end_sound=new Howl({src:[sound.url],volume:1,html5:true,});}
const buttonContent=`
            <div class="button__front">
                <span class="button__text">${sound.name}</span>
            </div>
    `;button.innerHTML=buttonContent;button.addEventListener('click',function(){settingEndSound.querySelectorAll('button').forEach((button,index)=>{button.classList.remove('current');});this.classList.add('current');end_sound=new Howl({src:[sound.url],volume:1,html5:true,});});settingEndSound.appendChild(button);});let start_sound=new Howl({src:[startSounds[0].url],volume:1,html5:true,});const settingStartSound=document.getElementById('setting-start-sound');startSounds.forEach((startSound,index)=>{let curentStartSound=new Howl({src:[startSound.url],volume:1,html5:true,});const button=document.createElement('button');button.className='difficulty__button';button.setAttribute('value',startSound.url);if(index==0){button.classList.add('current');}
const buttonContent=`
            <div class="button__front">
                <span class="button__text">${startSound.name}</span>
            </div>
    `;button.innerHTML=buttonContent;button.addEventListener('click',function(){settingStartSound.querySelectorAll('button').forEach((button,index)=>{button.classList.remove('current');});this.classList.add('current');start_sound=curentStartSound;});settingStartSound.appendChild(button);});const settingBackground=document.getElementById('setting-background');backgrounds.forEach((background,index)=>{const button=document.createElement('button');button.className='difficulty__button';button.setAttribute('value',background.url);if(index==0){button.classList.add('current');}
const buttonContent=`
            <div class="button__front">
                <span class="button__text">${background.name}</span>
                <img class="button__bg" src="${background.url}" alt="${background.name}" loading="lazy">
            </div>
    `;button.innerHTML=buttonContent;button.addEventListener('click',function(){settingBackground.querySelectorAll('button').forEach((button,index)=>{button.classList.remove('current');});this.classList.add('current');var viewportHeight=Math.max(document.documentElement.clientHeight||0,window.innerHeight||0);document.body.style.backgroundImage=`url(${background.url})`;document.body.style.backgroundSize='100% '+viewportHeight+'px';document.body.style.backgroundRepeat='no-repeat';});settingBackground.appendChild(button);});const changeBackgroundButton=document.getElementById('upload-background');const fileInput=document.getElementById('file-input');changeBackgroundButton.addEventListener('click',()=>{fileInput.click();});fileInput.addEventListener('change',()=>{const selectedFile=fileInput.files[0];if(selectedFile){const imageUrl=URL.createObjectURL(selectedFile);var viewportHeight=Math.max(document.documentElement.clientHeight||0,window.innerHeight||0);document.body.style.backgroundImage=`url(${background.url})`;document.body.style.backgroundSize='100% '+viewportHeight+'px';document.body.style.backgroundRepeat='no-repeat';}});let currentSpinDuration=10000;let timeButtons=document.querySelectorAll("#setting-time button");timeButtons.forEach((button,index)=>{button.addEventListener('click',function(){timeButtons.forEach((button,index)=>{button.classList.remove('current');});this.classList.add('current');currentSpinDuration=this.value;});});const sidebar=document.getElementById('sidebar');const saveButton=document.getElementById('button-save');const deleteButton=document.getElementById('button-delete');function createLoadButton(button_container,button_text,button_data,button_class){const customButton=document.createElement('button');customButton.classList.add('difficulty__button');customButton.setAttribute('value',button_data);const buttonFront=document.createElement('div');buttonFront.classList.add('button__front');const buttonText=document.createElement('span');buttonText.classList.add('button__text');buttonText.textContent=button_text;buttonFront.appendChild(buttonText);customButton.appendChild(buttonFront);if(button_class){customButton.classList.add('current');}
customButton.addEventListener('click',function(){if(button_container.classList.contains('default__buttons')){deleteButton.style.display='none';}else{deleteButton.style.display='block';}
const buttons=button_container.querySelectorAll('.difficulty__button');buttons.forEach(btn=>btn.classList.remove('current'));this.classList.add('current');const currentListDiv=document.getElementById('current-list');const items=Array.from(currentListDiv.querySelectorAll('div'));currentListDiv.innerHTML='';button_data.forEach(dataItem=>{const div=document.createElement('div');div.textContent=dataItem;currentListDiv.appendChild(div);});updateTemplateName(button_text);const itemsArray=createArrayFromDivContent();data=getData(itemsArray);render();});button_container.appendChild(customButton);}
function loadFromLocalStorage(){const buttonContainer=document.querySelector('.custom__buttons');buttonContainer.innerHTML='';const customListData=JSON.parse(localStorage.getItem('customList'))||[];customListData.forEach(item=>{document.getElementById('no-template').style.display='none';const name=item.name;const data=item.data;const customClass=item.class;createLoadButton(buttonContainer,name,data,customClass);});}
function deleteFromLocalStorage(nameToDelete){const savedData=JSON.parse(localStorage.getItem('customList'))||[];const updatedData=savedData.filter(item=>item.name!==nameToDelete);localStorage.setItem('customList',JSON.stringify(updatedData));}
function saveToLocalStorage(){const currentListDiv=document.getElementById('current-list');const items=Array.from(currentListDiv.querySelectorAll('div')).map(item=>item.textContent);const name=document.querySelector('#template-name').textContent;const savedData=JSON.parse(localStorage.getItem('customList'))||[];const updatedData=savedData.filter(item=>item.name!==name);updatedData.push({name,data:items});localStorage.setItem('customList',JSON.stringify(updatedData));console.log(localStorage.getItem('customList'));loadFromLocalStorage();}
saveButton.addEventListener('click',saveToLocalStorage);deleteButton.addEventListener('click',()=>{const nameToDelete=document.querySelector('#template-name').textContent;deleteFromLocalStorage(nameToDelete);loadFromLocalStorage();const currentListDiv=document.getElementById('current-list');currentListDiv.innerHTML='';list_default.forEach(itemData=>{const div=document.createElement('div');div.textContent=itemData.ticker;currentListDiv.appendChild(div);});updateTemplateName(text.write_template_name);const itemsArray=createArrayFromDivContent();data=getData(itemsArray);render();});const sortButton=document.getElementById('button-sort_by_alpha');sortButton.addEventListener('click',()=>{const currentListDiv=document.getElementById('current-list');const items=Array.from(currentListDiv.querySelectorAll('div'));items.sort((a,b)=>a.textContent.localeCompare(b.textContent));currentListDiv.innerHTML='';items.forEach(item=>currentListDiv.appendChild(item));const itemsArray=createArrayFromDivContent();data=getData(itemsArray);render();});const shuffleButton=document.getElementById('button-shuffle');shuffleButton.addEventListener('click',()=>{const currentListDiv=document.getElementById('current-list');const items=Array.from(currentListDiv.querySelectorAll('div'));for(let i=items.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[items[i],items[j]]=[items[j],items[i]];}
currentListDiv.innerHTML='';items.forEach(item=>currentListDiv.appendChild(item));const itemsArray=createArrayFromDivContent();data=getData(itemsArray);render();});function playSpinSound(){start_sound.volume(1);start_sound.play();}
function stopSpinSound(){start_sound.fade(1,0,1000);start_sound.stop();}
function playEndound(){end_sound.volume(1);end_sound.play();}
function stopEndSound(){end_sound.fade(1,0,1000);end_sound.stop();}
let current_list=[];let list_default=[{"ticker":"Mục 1"},{"ticker":"Mục 2"},{"ticker":"Mục 3"},{"ticker":"Mục 4"},{"ticker":"Mục 5"},{"ticker":"Mục 6"}];const buttons=Array.from(document.getElementsByClassName('difficulty__button'));const modal=document.getElementById('modal');const closeBtn=document.querySelector('.closeBtn');let data=getData(createArrayFromDivContent());console.log(data);function getRandomInt(min,max){min=Math.ceil(min);max=Math.floor(max);return Math.floor(Math.random()*(max-min))+min;}
function render(){const screenWidth=window.innerWidth;const screenHeight=window.innerHeight;const padding={top:0.1*screenHeight,right:0.1*screenWidth,bottom:0.1*screenHeight,left:0.1*screenWidth,};let width=screenWidth-padding.left-padding.right;let height=screenWidth-padding.left-padding.right;if(width>500){width=500;height=500;}
const radius=Math.min(width,height)/2;const spins=currentSpinDuration/1000;const degrees=spins*360;const color=d3.scaleOrdinal().domain(data.map(d=>d.name)).range(d3.quantize(t=>d3.interpolateSpectral(t*0.8+0.1),data.length).reverse())
let counter=0;let picked=1000;let fontSize='16px';if(data.length>200){fontSize='4px';}
if(data.length>100){fontSize='6px';}
else if(data.length>80){fontSize='8px';}
else if(data.length>60){fontSize='10px';}
else if(data.length>20){fontSize='12px';}
let svg=d3.select('#chart').selectAll('svg').data([null]);svg=svg.enter().append('svg').merge(svg).data([data]).attr('width',width).attr('height',height);let container=svg.select('.chartcontainer');if(container.empty()){container=svg.append('g').attr('class','chartcontainer').attr('transform',`translate(${width/2},${height/2})`);}else{container.attr('transform',`translate(${width/2},${height/2})`);}
const wheel=container.append('g').attr('class','wheel');const pie=d3.pie().sort(null).value(function(d){return 1;});const arc=d3.arc().innerRadius(0).outerRadius(radius);const arcs=wheel.selectAll('g.slice').data(pie).enter().append('g').attr('class','slice').attr("stroke","white");arcs.append('path').attr('fill',function(d,i){return color(i);}).attr('d',function(d){return arc(d);});arcs.append("text").attr("transform",function(d){d.innerRadius=0;d.outerRadius=radius;d.angle=(d.startAngle+d.endAngle)/2;return `rotate(${d.angle*180/Math.PI-90})translate(${d.outerRadius-10})`;}).attr("text-anchor","end").text(function(d,i){return data[i].ticker;}).attr('dy','0.35em').attr("fill-opacity",0.7).style('font-size',fontSize);const push=d3.select('#spin');push.on('click',spin);function spin(d){playSpinSound();counter++;const piedegree=360/data.length;const randomAssetIndex=getRandomInt(0,data.length);const randomPieMovement=getRandomInt(1,piedegree);rotation=(data.length-randomAssetIndex)*piedegree-randomPieMovement+degrees;wheel.transition().duration(currentSpinDuration).attrTween('transform',rotTween).ease(d3.easeCircleOut).on('end',function(){stopSpinSound();playEndound();let name=d3.select('.spin-result-name').data([null]);name=name.enter().append('text').attr('class','').merge(name).text(data[randomAssetIndex].ticker);let details=d3.select('#modal').data([null]);details=details.enter().merge(details).style('display','block');saveResult(data[randomAssetIndex].ticker);});}
function rotTween(){let i=d3.interpolate(0,rotation);return function(t){return `rotate(${i(t)})`;};}}
function getData(value){let array=[];for(let i=0;i<value.length;i++){array.push(value[i]);}
return array;}
function updateTemplateName(text){const title=document.getElementById('template-name');title.innerText=text;}
function updateCurrentList(itemsArray){const currentListDiv=document.getElementById('current-list');currentListDiv.innerHTML='';itemsArray.forEach(item=>{const div=document.createElement('div');div.textContent=item.ticker;currentListDiv.appendChild(div);});}
function createArrayFromDivContent(){const currentListDiv=document.getElementById('current-list');const items=Array.from(currentListDiv.querySelectorAll('div')).map(item=>{return{ticker:item.textContent};});return items;}
function watchCurrentListChanges(){const currentListDiv=document.getElementById('current-list');currentListDiv.addEventListener('input',()=>{const itemsArray=createArrayFromDivContent();data=getData(itemsArray);render();});}
watchCurrentListChanges();function closeModal(){modal.style.display='none';}
function outsideClick(e){if(e.target==modal){modal.style.display='none';}}
closeBtn.addEventListener('click',closeModal);window.addEventListener('click',outsideClick);window.addEventListener('touchend',outsideClick);window.onload=render;loadFromLocalStorage();default_data.forEach(item=>{const buttonContainer=document.querySelector('.default__buttons');const name=item.name;const data=item.data;const customClass=item.class;createLoadButton(buttonContainer,name,data,customClass)});const toggleButton=document.getElementById('toggle');toggleButton.addEventListener('click',()=>{const currentCollapseState=toggleButton.getAttribute('data-collapse');const newCollapseState=currentCollapseState==='on'?'off':'on';toggleButton.setAttribute('data-collapse',newCollapseState);if(newCollapseState==='on'){toggleButton.innerHTML='<span class="material-symbols-rounded">toggle_on</span> Thu gọn';document.getElementById('sidebar-data').style.display='none';document.getElementById('sidebar-template').style.display='none';document.getElementById('sidebar-setting').style.display='none';document.getElementById('embed').style.display='none';document.getElementById('share').style.display='none';document.querySelector('header').style.display='none';document.querySelector('article').style.display='none';document.querySelector('.site-footer').style.display='none';}else{toggleButton.innerHTML='<span class="material-symbols-rounded">toggle_off</span> Thu gọn';document.getElementById('sidebar-data').style.display='block';document.getElementById('sidebar-template').style.display='block';document.getElementById('sidebar-setting').style.display='block';document.getElementById('embed').style.display='block';document.getElementById('share').style.display='block';document.querySelector('header').style.display='block';document.querySelector('article').style.display='block';document.querySelector('.site-footer').style.display='block';}});function saveResult(text){document.getElementById('sidebar-result').style.display='block';const result_list=document.getElementById('result-list');const div=document.createElement('div');div.textContent=text;result_list.appendChild(div);}
const deleteResultButton=document.getElementById('button-delete-result');deleteResultButton.addEventListener('click',()=>{const result_list=document.getElementById('result-list');result_list.innerHTML='';});function getDataURL(){let heading=document.getElementById("template-name").textContent.trim();let data='';const currentListDiv=document.getElementById('current-list');currentListDiv.querySelectorAll('div').forEach(item=>{data=data+","+item.textContent;});data=data.slice(1);console.log(data);const jsonObject={heading:heading,data:data};const jsonString=btoa(unescape(encodeURIComponent(JSON.stringify(jsonObject))));console.log(jsonString);let url=text.home+'?d='+jsonString;return url;}
function copyTextToClipboard(text){const tempInput=document.createElement("textarea");tempInput.value=text;document.body.appendChild(tempInput);tempInput.select();document.execCommand("copy");document.body.removeChild(tempInput);}
let share_button=document.getElementById('share');if(share_button){if(navigator.share){share_button.addEventListener('click',()=>{navigator.share({title:document.title,text:document.title,url:getDataURL(),});});}else{share_button.style.display='none';}}
let embed_button=document.getElementById('embed');if(embed_button){embed_button.addEventListener('click',()=>{let url=getDataURL()+'&embed';let embed='<iframe width="100%" height="600"  src="'+url+'" style="max-width:100%; max-height:100%;" frameborder="0" allow="accelerometer" allowfullscreen></iframe>';copyTextToClipboard(embed);alert(text.embed_copied);});}
const currentURL=window.location.href;if(currentURL.includes('&embed')){toggleButton.click();}